version: 2.0

jobs:
  noop:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - run: echo "Noop Do nothing."

  setup:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout # check out the code in the project directory

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install
      - run: cp yarn.lock yarn.lock.tmp
      - run: yarn add cypress
      - run: rm yarn.lock
      - run: mv yarn.lock.tmp yarn.lock

      - save_cache:
          paths:
            - node_modules
            - ~/.cache
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  build:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      # build
      - run:
          name: Build site
          command: yarn build

      - persist_to_workspace:
          root: ./
          paths:
            - build

  test:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run:
          name: Unit test
          command: yarn test:ci --runInBand --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: 'reports/junit'
            JEST_JUNIT_OUTPUT_NAME: 'js-test-results.xml'

      - store_test_results:
          path: reports/junit

      - store_artifacts:
          path: reports/junit

  teste2e:
    docker:
      - image: circleci/node:12.14.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - attach_workspace:
          at: ./

      - run:
          name: Install Cypress dependencies
          command: sudo apt-get install -yq libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run:
          name: Run All Tests with Coverage Reports
          command: sh ./.circleci/e2e-test.sh

      - store_artifacts:
          path: coverage-report/lcov-report

workflows:
  version: 2
  install-build-and-test:
    jobs:
      - noop:
          filters:
            branches:
              ignore: master

      - setup
      - test:
          requires:
            - setup
      - teste2e:
          requires:
            - build
      - build:
          requires:
            - setup
