name: CI
on: ['push', 'pull_request']
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModulesCypress-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModulesCypress-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Install Cypress dependencies
        run: sudo apt-get install -yq libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Run All Tests with Coverage Reports
        run: sh ./.circleci/e2e-test.sh
        env:
          CI: true
